### ISSUE TITLE
plugin does not build with IOS 11

### ISSUE THREAD

**Issue by ssossou** [abritopach/capacitor-youtube-player#1]
when trying to use capacitor youtube player i noticed it was trowing an error for ios 11 target deployment
![Screen Shot 2019-04-25 at 1 23 04 PM](https://user-images.githubusercontent.com/340387/56755331-4cd29780-675d-11e9-97af-285e3ce4414a.png)

**Comment by abritopach** [comment]
Good morning @ssossou 

I've had a lot of trouble at work and haven't been able to devote time to the plugin.

Thanks for the report. 

I'll check it out.

**Comment by abritopach** [comment]
Fixed in "version": "1.0.0-alpha.1-14"
