### ISSUE TITLE
BuildConfig not found

### ISSUE THREAD

**Issue by alexlarraga1** [abritopach/capacitor-youtube-player#11]
`
Ionic:

   Ionic CLI                     : 5.4.2 (D:\User\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.2.1
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 9.1.8
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (D:\Program Files (x86)\Android\android-sdk)
   NodeJS            : v12.18.0 (D:\Program Files\nodejs\node.exe)
   npm               : 6.14.5
   OS                : Windows 10
`

I have this Error 

> PROJECT_DIR\node_modules\capacitor-youtube-player\android\capacitor-youtube-player\src\main\java\com\abpjap\plugin\youtubeplayer\YoutubePlayerFragment.java:22: error: cannot find symbol
> private YouTubePlayer youTubePlayer;
>                         ^
> symbol:   variable "MY_API_KEY"
> location: class BuildConfig

**Comment by abritopach** [comment]
Hi @alexlarraga1,

Check this section of the documentation: 

https://github.com/abritopach/capacitor-youtube-player#important-note-android

---

To use the CAPACITOR YOUTUBE PLAYER plugin you need to add the YOUTUBE API KEY in the file gradle.properties.

`YOUTUBE_API_KEY="YOUR_YOUTUBE_API_KEY"`

---

Reference: https://developers.google.com/youtube/registering_an_application?hl=es-419

**Comment by alexlarraga1** [comment]
Hi @abritopach 

I put 
`YOUTUBE_API_KEY = KEYWITHOUTQUOTES`
in my gradle.properties, but it should have been 
`YOUTUBE_API_KEY=KEYWITHQUOTES`
