### ISSUE TITLE
Exposed Google API keys

### ISSUE THREAD

**Issue by rsgyan** [abritopach/capacitor-youtube-player#158]
I built an ionic 6 capacitor 3 app with this plugin, it worked fine until just recently it stoped working on android. Google started blocking the app because they said my app was exposing  GCP API keys. How can I fix this?

**Comment by abritopach** [comment]
@rsgyan  The problem is that you are using an "API KEY" in the code and you have published the application with that API KEY.

API KEYs have to be secret.
