### ISSUE TITLE
More example/details required for using Capacitor Youtube API with Ionic 4 for Android and iOS app

### ISSUE THREAD

**Issue by Madhulika08** [abritopach/capacitor-youtube-player#2]
The documentation is not proving to be enough to implement Capacitor Youtube API in my app using Ionic 4.
Can we have a demo app or some more detail on how to play video in the app using this API

**Comment by abritopach** [comment]
Good morning @Madhulika08 

I've had a lot of trouble at work and haven't been able to devote time to the plugin.

I will try to update the project and the documentation during this week.

For now I leave you the link to a repository where the plugin is used.

https://github.com/abritopach/angular-ionic-ngxs-movies/blob/master/src/app/modals/youtube-modal/youtube.modal.ts

Any suggestion is welcome.

Any doubt ask me.

**Comment by abritopach** [comment]
Hello @Madhulika08 

I have added a new section in the readme: Using this plugin

https://github.com/abritopach/capacitor-youtube-player#using-this-plugin

Also I have created an example project where the plugin is used:

https://github.com/abritopach/ionic-test-capacitor-youtube-player
