### ISSUE TITLE
Capacitor does not work in device

### ISSUE THREAD

**Issue by Sevensnake** [abritopach/capacitor-youtube-player#26]
I always return undefined error. runs good on web but not on android device. Will there be a fix or is this project dead?

**Comment by abritopach** [comment]
@Sevensnake  The project is not dead. But one cannot always keep an eye on updating / improving an open source project if you combine it with a job. And even more so if people don't contribute either.

If you specify what kind of error it gives you and provide more information perhaps the problem it is giving you can be replicated.

**Comment by Sevensnake** [comment]
Thank you for your response. The error I am getting now.
No variants found for 'capacitor-youtube-player'. Check build files to ensure at least one variant exists.

**Comment by Sevensnake** [comment]
I added the import to the MainActivity.java and it does not recognize

`import com.abpjap.plugin.youtubeplayer.YoutubePlayer;
import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;


import java.util.ArrayList;

public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
      add(YoutubePlayer.class);
    }});
  }
}`

**Comment by miguelsignes** [comment]
Same error. MainActivy.java does not recognize import plugin.

**Comment by abritopach** [comment]
@Sevensnake @miguelsignes 

The steps you have to follow to use the plugin are the following:

1) npm install --save capacitor-youtube-player@latest
2) npx cap sync

I will update the guide so that there is no confusion.
