### ISSUE TITLE
Support for Capacitor 2.X

### ISSUE THREAD

**Issue by aces-tm** [abritopach/capacitor-youtube-player#31]
It seems that the plugin doesn't work with Capacitor 2.x for Android devices. When I try to build the app I get error in `YoutubePlayer.java` with the following line 
`import com.getcapacitor.annotation.CapacitorPlugin;`

`annotation` comes with the error `Cannot resolve symbol 'annotation'`

Any help with this?

**Comment by abritopach** [comment]
Hi @aces-tm 

The plugin works for capacitor version 2.0 until it was upgraded to version 3.0.

If you want to continue using version 2.0 I have created a version.

For this you have to install:

`npm install --save capacitor-youtube-player@1.0.0-support-capacitor2`
