### ISSUE TITLE
Not possible to control the player ?

### ISSUE THREAD

**Issue by fritsc3** [abritopach/capacitor-youtube-player#33]
Hello,

I am trying to change the player attributes by using **playerVars** in the initialize method.
But it seems not to work.

![image](https://user-images.githubusercontent.com/66488926/112828608-398a7e00-9090-11eb-84ba-ce0d35d20016.png)

My coding:

    const options = {
      playerId: 'YT',
      playerSize: {
        width: 200,
        height: 200
      },
      playerVars: {
        controls: 0,
        modestbranding: 0,
        autoplay: 1,
        rel: 0,
        showinfo: 1,
      },
      videoId: 'HcDad4y0dlo',
    };

    const result: any = await YoutubePlayerWeb.initialize(options);

I have tried various options, but the player looks always the same.

Any ideas? Should this work or is it a bug?

Thanks!
Nils

**Comment by abritopach** [comment]
Hello @fritsc3  

Sorry for replying so late :(

This is indeed a bug and has been fixed in version [1.0.7](https://github.com/abritopach/capacitor-youtube-player/releases/tag/1.0.6)

I have updated the example in ionic where the following parameters are passed to the player:

```
async initializeYoutubePlayerPluginWeb() {
    console.log('HomePage::initializeYoutubePlayerPluginWeb() | method called');
    const options: IPlayerOptions = {
      playerId: 'youtube-player',
      playerSize: {width: 640, height: 360},
      playerVars: {
        autoplay: 1,
        rel: 0,
        showinfo: 1
      },
      videoId: 'tDW2C6rcH6M',
      fullscreen: false,
      debug: true
    };
    const result = await YoutubePlayer.initialize(options);
    console.log('playerReady', result);
    ...
```

Thank you for reporting it.
