### ISSUE TITLE
Adding to Capacitor V3 project - doesn't show up in Android studio

### ISSUE THREAD

**Issue by daveshirman** [abritopach/capacitor-youtube-player#35]
I've got a Capacitor V3 project Android, I ran:

`npm install --save capacitor-youtube-player@latest`

then

`npx cap sync`

Tried this a couple of times and the plugin is still not present in my Android Studio project - as in not even listed on the left project explorer panel.

I can see that it **is** present in my `node_modules` folder though.

I build the project and it runs but when I call init as per your setup instructions:
`YoutubePlayer.initialize(options);`

I get YoutubePlayer undefined.

Anything I'm missing?

**Comment by abritopach** [comment]
@daveshirman  I am sorry I did not respond sooner.

Have you tried deleting the android folder and generating it again?

What is the project developed on? Can you give more details?

**Comment by daveshirman** [comment]
It's ok. It's an Ionic 5 and Capacitor project.

I just used the YouTube iframe player instead and got round the issue.

Thanks.
