### ISSUE TITLE
Cannot read property 'initialize' of undefined

### ISSUE THREAD

**Issue by danielv6987** [abritopach/capacitor-youtube-player#4]
Hi,
I tried to include this plugin into my project but it seems like the plugin is not part of the capacitor plugins. I only tried on Android (Emulator)

`import { Plugins, Capacitor } from "@capacitor/core`

I also tried running the example project but got the same results. Not sure if I'm missing another step.

`ionic build`
`npx cap add android`
`npx cap open android`

Also tried running
`npx cap sync`

Thank you,
Daniel

**Comment by danielv6987** [comment]
Hi,
I got the player to initialize on Android (Emulator) by adding the class to the project's MainActivity.java
` this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
      add(YoutubePlayer.class);
    }});`

but now it's failing to initialize. I will keep looking into this, any help is appreciated.

Thank you,
Daniel

**Comment by danielv6987** [comment]
Hi,
I downloaded a new emulator and the plugin is working. The new emulator does have Play Store enabled. 

Thank you,
Daniel

**Comment by abritopach** [comment]
Hi @danielv6987 

In the official Capacitor documentation appears how to register the plugin:

https://capacitor.ionicframework.com/docs/plugins/android#export-to-capacitor

I'll add it to the readme.

Thank you,

Adrián.
