### ISSUE TITLE
Youtube Player events

### ISSUE THREAD

**Issue by danielv6987** [abritopach/capacitor-youtube-player#5]
Hi,
Looking at the web.js file in this package it looks like you are consuming the events.
```
onReady
onStateChange
onReady
onError
```
I tried adding a listener on the YoutubePlayerWeb object. The callbacks are not being called. Since it seems like you are only listening to events and just console.log the results, can you please allow us to pass the event listeners as options when the player is first initialized? 

Thank you,
Daniel

**Comment by abritopach** [comment]
Hi @danielv6987

When initializing a youtube player you can add an event listener as follows:

```
async initializeYoutubePlayerPluginWeb() {

    const options = {playerId: 'youtube-player', playerSize: {width: 640, height: 360}, videoId: 'tDW2C6rcH6M'};
    const result = await YoutubePlayerWeb.initialize(options);

    result.player.addEventListener('onPlaybackQualityChange', (event) => {
      console.log('playback quality is', event);
    });

    result.player.addEventListener('onStateChange', (event) => {
      console.log('state is', event);
    });

    /* Others events */
 }
```
YoutubePlayerWeb.initialize(options) returns the created player.

You can look at the following example project: https://github.com/abritopach/ionic-test-capacitor-youtube-player
